import 'package:crossfit/styles/colors.dart';
import 'package:flutter/material.dart';

ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  primarySwatch: MaterialColor(darkPurple.value, const {
    50: Color(0xFFEDE7F6),
    100: Color(0xFFD1C4E9),
    200: Color(0xFFB39DDB),
    300: Color(0xFF9575CD),
    400: Color(0xFF7E57C2),
    500: Color(0xFF673AB7),
    600: Color(0xFF5E35B1),
    700: Color(0xFF512DA8),
    800: Color(0xFF4527A0),
    900: Color(0xFF311B92),
  }),
  primaryColor: darkPurple,
  primaryColorLight: const Color(0xFFD1C4E9),
  primaryColorDark: mildPurple,
  canvasColor: darkGrey,
  scaffoldBackgroundColor: darkGrey,
  bottomAppBarColor: darkGreyContrast,
  cardColor: darkGreyContrast,
  dividerColor: lightGrey,
  highlightColor: lightGreyContrast,
  splashColor: grey,
  selectedRowColor: dullWhite,
  unselectedWidgetColor: verylightGrey,
  disabledColor: dullGreyContrast,
  toggleableActiveColor: darkPurple,
  secondaryHeaderColor: dullGrey,
  backgroundColor: dullGrey,
  dialogBackgroundColor: darkGreyContrast,
  indicatorColor: darkPurple,
  hintColor: dullGreyContrast,
  errorColor: brightRed,
  colorScheme: ColorScheme.dark(
    primary: darkPurple,
    secondary: darkPurple,
    surface: darkGrey,
    background: darkGrey,
    error: brightRed,
    onPrimary: white,
    onSecondary: white,
    onSurface: white,
    onBackground: white,
    onError: white,
    brightness: Brightness.dark,
  ),
  
);
